### ISSUE TITLE
FYI unattributed reuse

### ISSUE THREAD

**Issue by ptim** [rstacruz/startup-name-generator#5]
I know this is MIT licensed, but thought you might like to know:

https://www.producthunt.com/posts/nameland

**Comment by rstacruz** [comment]
Whoa thanks! The package itself that generates names is MIT licenced, but this person stole [my Codepen](https://codepen.io/rstacruz/pen/wJyaJb) for the styling and markup. Not cool.

![image](https://user-images.githubusercontent.com/74385/132216475-b5f3edff-cc73-49e2-9d84-146c43c7191a.png)

**Comment by ptim** [comment]
That's what I thought! Love your work
